name: 'Basecamp - Notify ready for review'
description: 'Use basecamp chatbots to notify when a pull request are ready to review'
branding:
  color: purple
  icon: message-circle
inputs:
  account_id:
    description: 'Basecamp account id'
    required: true
    default: ''
  bucket_id:
    description: 'Basecamp bucket id'
    required: true
    default: ''
  chat_id:
    description: 'Basecamp chat id'
    required: true
    default: ''
  notify_open:
    description: 'Notify when a pull request is open'
    required: false
    default: false
  notify_open_when_draft:
    description: 'Notify when a pull request is open even if it is a draft pull request'
    required: false
    default: false
  custom_template:
    description: 'Customize messages that will be published on basecamp'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'